export enum KeyActiveBattleMenu {
  BATTLE_MAIN = 'BATTLE_MAIN',
  BATTLE_MOVE_SELECT = 'BATTLE_MOVE_SELECT',
  BATTLE_ITEM = 'BATTLE_ITEM',
  BATTLE_SWITCH = 'BATTLE_SWITCH',
  BATTLE_FLEE = 'BATTLE_FLEE'
}
